require_relative '../lib/autorent_system'

DELTA = 1e-15
CLIO_LICENSE_PLATE = 'AAA001'
FORD_KA_LICENSE_PLATE = 'AAA002'
LOGAN_LICENSE_PLATE = 'AAA003'
DUSTER_LICENSE_PLATE = 'AAA004'
DUSTER_FULL_TANK = 70
KA_FULL_TANK = 40
CLIO_FULL_TANK = 45
KA_20_PERCENT_TANK = 8
KA_40_PERCENT_TANK = 16
KA_60_PERCENT_TANK = 24
KA_80_PERCENT_TANK = 32
LOGAN_FULL_TANK = 50
MAX_KM_ALLOWED_PER_DAY = 400
TRAVELLED_300_KMS = 300
LOGAN_COST_PER_EXCEEDED_KM = 12
LOGAN_RENT_COST = 500
FORD_KA_RENT_COST = 430
DUSTER_RENT_COST = 700
CLIO_RENT_COST = 400
CLIO_RENT_COST_PER_EXCEEDED_KM = 10
CLIO_80_PERCENT_TANK = 36
FLUENCE_LICENSE_PLATE = 'AAA003'
FLUENCE_RENT_COST = 600
FLUENCE_RENT_COST_PER_EXCEEDED_KM = 18
FLUENCE_80_PERCENT_TANK = 48

#Creates an AutorentSystem, that has all the data that was mentioned in the exercise assignment.
#return an AutorentSystem
def create_system_using_data_from_the_exercise_assignment
  raise NotImplementedError.new("Not implemented yet!!")
end
